In [11]:
import numpy as np

# 1. Arrays

## One Dimension

In [12]:
np.array([1,4,5,7,4,2,0])

array([1, 4, 5, 7, 4, 2, 0])

## Two Dimension

In [13]:
np.array([1,4,5,7,4,2,0])

array([1, 4, 5, 7, 4, 2, 0])

### Addressing an Array

In [14]:
x = np.array([1,4,5,7,4,2,0])

In [15]:
# second element
x[1]  # index starts with 0

4

In [16]:
# first five
x[:5]

array([1, 4, 5, 7, 4])

In [17]:
# second to fifth  
x[1:5]  # index starts with 0

array([4, 5, 7, 4])

In [18]:
# Last  
x[-1]

0

In [19]:
# Last three
x[-3:]

array([4, 2, 0])

In [20]:
# All but last two
x[:-2]

array([1, 4, 5, 7, 4])