In [2]:
import numpy as np

## 1. Arrays

### One Dimension

In [3]:
np.array([1,4,5,7,4,2,0])

array([1, 4, 5, 7, 4, 2, 0])

### Two Dimesion

In [4]:
np.array([1,4,5,7,4,2,0])

array([1, 4, 5, 7, 4, 2, 0])

Addressing an Array

In [5]:
x = np.array([1,4,5,7,4,2,0])

In [6]:
# second element
x[1]  # index starts with 0

4

In [7]:
# first five
x[:5]

array([1, 4, 5, 7, 4])

In [8]:
# second to fifth  
x[1:5]  # index starts with 0

array([4, 5, 7, 4])

In [9]:
# Last  
x[-1]

0

In [10]:
# Last three
x[-3:]

array([4, 2, 0])

In [11]:
# All but last two
x[:-2]

array([1, 4, 5, 7, 4])